# Generated by Django 4.1.5 on 2023-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Полный текст')),
            ],
        ),
    ]
